name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - run: echo $IMAGE_TAG
      id: Echo Image Tag
      with:
        IMAGE_TAG: ${{ env.GITHUB_RUN_NUMBER }}