name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - run: |
        echo "$IMAGE_TAG"
        echo "again"
      id: build-image
      env:
        IMAGE_TAG: ${{ env.GITHUB_RUN_NUMBER	 }}