name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - run: |
        echo "GITHUB_RUN_ID"
        echo "$GITHUB_RUN_ID"
        echo ""
        echo "GITHUB_RUN_NUMBER"
        echo "$GITHUB_RUN_NUMBER"
        echo ""
        echo "GITHUB_SHA"
        echo "$GITHUB_SHA"
      id: build-image