name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - run: |
        echo "running"
        echo "$GITHUB_RUN_ID"
        echo "ran"
      id: build-image